all: 2.1.1 2.1.2 2.2.1 2.2.2 2.3.1 2.3.2

2.1.1:
	gcc -pthread -o 2.1.1.o 2.1.1.c
2.1.2:
	gcc -pthread -o 2.1.2.o 2.1.2.c
2.2.1:
	gcc -pthread -o 2.2.1.o 2.2.1.c
2.2.2:
	gcc -pthread -o 2.2.2.o 2.2.2.c
2.3.1:
	gcc -pthread -o 2.3.1.o 2.3.1.c
2.3.2:
	gcc -pthread -o 2.3.2.o 2.3.2.c
clean:
	rm -f *.o